/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Presentacion;

/**
 *
 * @author pc
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);//maximizamos el formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuAlmacen = new javax.swing.JMenu();
        mnuCategorias = new javax.swing.JMenuItem();
        mnuArticulos = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenu();
        mnuProveedores = new javax.swing.JMenuItem();
        mnuIngresos = new javax.swing.JMenuItem();
        mnuCVentas = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenuItem();
        mnuAcceso = new javax.swing.JMenu();
        mnuRoles = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuSalirS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mnuAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/almacen.png"))); // NOI18N
        mnuAlmacen.setText("Almacen");

        mnuCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuCategorias.setText("Categorias");
        mnuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriasActionPerformed(evt);
            }
        });
        mnuAlmacen.add(mnuCategorias);

        mnuArticulos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuArticulos.setText("Articulos");
        mnuArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArticulosActionPerformed(evt);
            }
        });
        mnuAlmacen.add(mnuArticulos);

        menuBar.add(mnuAlmacen);

        mnuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/compras.png"))); // NOI18N
        mnuCompras.setText("Compras");

        mnuProveedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuProveedores.setText("Proveedores");
        mnuCompras.add(mnuProveedores);

        mnuIngresos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuIngresos.setText("Ingresos");
        mnuCompras.add(mnuIngresos);

        menuBar.add(mnuCompras);

        mnuCVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/ventas.png"))); // NOI18N
        mnuCVentas.setText("Ventas");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuClientes.setText("Clientes");
        mnuCVentas.add(mnuClientes);

        mnuVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuVentas.setText("Ventas");
        mnuCVentas.add(mnuVentas);

        menuBar.add(mnuCVentas);

        mnuAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/acceso.png"))); // NOI18N
        mnuAcceso.setText("Acceso");

        mnuRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuRoles.setText("Roles");
        mnuRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRolesActionPerformed(evt);
            }
        });
        mnuAcceso.add(mnuRoles);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Usuarios");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuAcceso.add(jMenuItem7);

        menuBar.add(mnuAcceso);

        mnuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/consulta.png"))); // NOI18N
        mnuConsultas.setText("Consultas");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setText("Consulta Compras");
        mnuConsultas.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem9.setText("Consulta Ventas");
        mnuConsultas.add(jMenuItem9);

        menuBar.add(mnuConsultas);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/cerrar-sesion.png"))); // NOI18N
        mnuSalir.setText("Salir");

        mnuSalirS.setText("Salir");
        mnuSalirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirSActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuSalirS);

        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriasActionPerformed
        // generamos una instancia al formulario categoria
        FrmCategoria fc = new FrmCategoria();
        contenedor.add(fc);
        fc.setVisible(true);
    }//GEN-LAST:event_mnuCategoriasActionPerformed

    private void mnuArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArticulosActionPerformed
       frmArticulos fa = new frmArticulos();
        contenedor.add(fa);
        fa.setVisible(true);
    }//GEN-LAST:event_mnuArticulosActionPerformed

    private void mnuRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRolesActionPerformed
        // TODO add your handling code here:
        FrmRol rol = new FrmRol();
        contenedor.add(rol);
        rol.setVisible(true);
    }//GEN-LAST:event_mnuRolesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
            frmUsuario u = new frmUsuario();
            contenedor.add(u);
            u.setVisible(true);
            
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cargarOpciones();
    }//GEN-LAST:event_formWindowOpened

    private void mnuSalirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirSActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirSActionPerformed

    private void cargarOpciones(){
        if(Negocio.Variables.rolNombre.equals("Administrador")){
            mnuAlmacen.setEnabled(true);
            mnuCompras.setEnabled(true);
            mnuVentas.setEnabled(true);
            mnuAcceso.setEnabled(true);
            mnuCompras.setEnabled(true);
            mnuCVentas.setEnabled(true);
        }else if(Negocio.Variables.rolNombre.equals("Bodeguero")){
            mnuAlmacen.setEnabled(true);
            mnuCompras.setEnabled(true);
            mnuVentas.setEnabled(false);
            mnuAcceso.setEnabled(false);
            mnuCompras.setEnabled(true);
            mnuCVentas.setEnabled(false);
        }else if(Negocio.Variables.rolNombre.equals("Vendedor")){
            mnuAlmacen.setEnabled(false);
            mnuCompras.setEnabled(false);
            mnuVentas.setEnabled(true);
            mnuAcceso.setEnabled(false);
            mnuCompras.setEnabled(false);
            mnuCVentas.setEnabled(true);
        }else{
            mnuAlmacen.setEnabled(false);
            mnuCompras.setEnabled(false);
            mnuVentas.setEnabled(false);
            mnuAcceso.setEnabled(false);
            mnuCompras.setEnabled(false);
            mnuCVentas.setEnabled(false);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAcceso;
    private javax.swing.JMenu mnuAlmacen;
    private javax.swing.JMenuItem mnuArticulos;
    private javax.swing.JMenu mnuCVentas;
    private javax.swing.JMenuItem mnuCategorias;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenu mnuCompras;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuItem mnuIngresos;
    private javax.swing.JMenuItem mnuProveedores;
    private javax.swing.JMenuItem mnuRoles;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem mnuSalirS;
    private javax.swing.JMenuItem mnuVentas;
    // End of variables declaration//GEN-END:variables

}
